config/routes.rb
Rails.application.routes.draw do
  resources :bets
  get 'static_pages/chat'

  resources :roles
  devise_for :users
  scope "/admin" do
  resources :users
  end
  resources :categories
  resources :posts do 
    resources :comments
  end
  resources :games
  resources :competitions
  resources :teams
  get 'welcome/index'

  resources :players

  root 'welcome#index'
 

end

app/models/competition.rb
class Competition < ActiveRecord::Base
  has_many :teams  
  validates :name, presence: true,
                  length: { minimum: 5 }
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  load_and_authorize_resource

  # GET /competitions
  # GET /competitions.json
  def index
    @competitions = Competition.all
    @competitions = Competition.page(params[:page]).per(1)
    
   

  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
    @competition = Competition.find(params[:id])
    @teams = Team.where(comp_id: @competition.id)
  end

  # GET /competitions/new
  def new
  end
  # GET /competitions/1/edit
  def edit
  end

  # POST /competitions
  # POST /competitions.json
  def create
    
    respond_to do |format|
      if @competition.save
        format.html { redirect_to @competition, notice: 'Competition was successfully created.' }
        format.json { render :show, status: :created, location: @competition }
      else
        format.html { render :new }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competitions/1
  # PATCH/PUT /competitions/1.json
  def update
    respond_to do |format|
      if @competition.update(competition_params)
        format.html { redirect_to @competition, notice: 'Competition was successfully updated.' }
        format.json { render :show, status: :ok, location: @competition }
      else
        format.html { render :edit }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    @competition.destroy
    respond_to do |format|
      format.html { redirect_to competitions_url, notice: 'Competition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # Never trust parameters from the scary internet, only allow the white list through.
    def competition_params
      params.require(:competition).permit(:name, :description, :country)
    end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_form.html.erb
<%= form_for(@competition) do |f| %>
  <% if @competition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

      <ul>
      <% @competition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%=f.select :country, "<option>England</option><option>VietNam</option>".html_safe%>
  </div>
  <br>
  <div >
    <%= f.submit nil, :class => 'btn btn-primary'%>
  </div>
<% end %>

app/views/competitions/edit.html.erb
<h1>Editing Competition</h1>

<%= render 'form' %>

<br>
<%= link_to 'Back', competitions_path,:class => 'btn btn-primary btn-md' %>

app/views/competitions/index.html.erb
<script>
  $(function() {
    $('table').tablesort().data('tablesort');
    $('thead th.number').data('sortBy', function(th, td, sorter) {
      return parseInt(td.text(), 10);
    });
  });
</script>




<%= link_to 'New Competition', new_competition_path,:class => 'btn btn-primary' %> | 
<%= link_to 'New Team', new_team_path,:class => 'btn btn-primary' %>
<table>
  <thead>
    <tr>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @competitions.each do |competition| %>
      <tr>
        
        <td><%= competition.description %></td>
        <td><%= competition.country %></td>
        <h4><%=competition.name%> Table</h4>
    
      </tr>


  <table class ="table table-bordered table-striped " width="50%"  >
  <thead>
  <tr>
    <th><Team Name%></th>
   <!--  <th>Game played</th>
    <th>Game remaining</th> -->
    <th>Win</th>
    <th>Lose</th> 
    <th>Tie</th>
    <th>Score</th>
    
  </tr>
  </thead>
  <tbody>
  <%@teams = Team.where(comp_id: competition.id)%>
  <%@teams.each do |team|%>

  <tr>
    <td><%=image_tag(team.team_picture_url, :width => 20)%> <%=link_to team.name, team%></td>
   <!--  <td><%=38 -   team.not_kick_off%>
    <td><%=team.not_kick_off%> -->
    <td><%=team.wins%></td>
    <td><%=team.losses%></td> 
    <td><%=team.ties%></td>
    <td><%=team.score%></td>
    
  </tr>

</tbody>
  <%end%>
</table>


        <td><%= link_to 'Show', competition ,:class => 'btn btn-primary btn-md'%></td>
        <td><%= link_to 'Edit', edit_competition_path(competition),:class => 'btn btn-primary btn-md' %></td>
        <td><%= link_to 'Destroy', competition, method: :delete, data: { confirm: 'Are you sure?' },:class => 'btn btn-danger btn-md' %></td>
     
    <% end %>
  </tbody>
  <br>
  <%= paginate @competitions %>
</table>


<br>

app/views/competitions/new.html.erb
<h1>New Competition</h1>

<%= render 'form' %>

<%= link_to 'Back', competitions_path,:class => 'btn btn-primary btn-md' %>

app/views/competitions/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @competition.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @competition.description %>
</p>

<p>
  <strong>Country:</strong>
  <%= @competition.country %>
</p>
<h2>League Table</h2>
<table style="width:37%" class="table table-striped">
  
  <tr>
    <th>Team</th>
    <!-- <th>Game played</th>
    <th>Game remaining</th> -->
    <th>Win</th>
    <th>Lose</th> 
    <th>Tie</th>
    <th>Point</th>
    
  </tr>
  <%@teams.each do |team|%>
  <tr>
    <td><%=image_tag(team.team_picture_url, :width => 20)%> <%=link_to team.name, team%></td>
   <!--  <td><%=38 -   team.not_kick_off%>
    <td><%=team.not_kick_off%> -->
    <td><%=team.wins%></td>
    <td><%=team.losses%></td> 
    <td><%=team.ties%></td>
    <td><%=team.wins*3+team.ties%></td>
    
  </tr>
  <%end%>
</table>
<p>
	<strong>Teams of league</strong><br>
	<% @teams.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |p| %>
      <div class="col-md-1">
        <br><br>
	<tr>
  <td><%= link_to( image_tag(p.team_picture_url, :width => 70, :height => 70), team_path(p), :class=>"work") if p.team_picture.present?%></td><br>
	<td><%=link_to p.name, team_path(p.id)%></td><br>
	</tr>
  </div>
  <%end%>
  </div>
  <%end%>
</p>

<%= link_to 'Edit', edit_competition_path(@competition),:class => 'btn btn-primary btn-md' %> |
<%= link_to 'Back', competitions_path ,:class => 'btn btn-primary btn-md'%>