config/routes.rb
Rails.application.routes.draw do
  resources :bets
  get 'static_pages/chat'

  resources :roles
  devise_for :users
  scope "/admin" do
  resources :users
  end
  resources :categories
  resources :posts do 
    resources :comments
  end
  resources :games
  resources :competitions
  resources :teams
  get 'welcome/index'

  resources :players

  root 'welcome#index'
 

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :home_team, class_name: 'Team', foreign_key: 'home_team_id'
  belongs_to :away_team, class_name: 'Team', foreign_key: 'away_team_id'
  validates :home_team_score, presence: true
  validates :away_team_score, presence: true
  validate :home_and_away_teams_are_different

  has_one :bet
  def winner
    return home_team.name if home_team_score > away_team_score
    return away_team.name if away_team_score > home_team_score     
    return 'not_kick_off' if (home_team_score == -1 && away_team_score ==-1)
    return 'tie' if (home_team_score == away_team_score && home_team_score!= -1 && away_team_score!=-1)
  end

  def result(team)
    if winner == 'tie'
      return 'T'
    elsif winner == 'not_kick_off'
      return 'N'
    elsif winner == team
      return 'W'
    else 
      return 'L' 
     end
  end

  def home_and_away_teams_are_different
    if home_team_id == away_team_id
      errors.add(:away_team_id, "must be different from home team")
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  load_and_authorize_resource

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
 
    @teams = Team.all
  end

  # GET /games/1/edit
  def edit
    @teams = Team.all
  end

  # POST /games
  # POST /games.json
  def create
    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:home_team_id, :away_team_id, :home_team_score, :away_team_score, :date)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :home_team_id %><br>
    <%= @game.home_team.name %>
  </div>
  <div class="field">
    <%= f.label :away_team_id %><br>
    <%= @game.away_team.name%>
  </div>
  <div class="field">
    <%= f.label :home_team_score %><br>
    <%= f.number_field :home_team_score %>
  </div>
  <div class="field">
    <%= f.label :away_team_score %><br>
    <%= f.number_field :away_team_score %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit nil,:class => 'btn btn-primary btn-md' %>
  </div>
<% end %>


<%= link_to 'Show', @game ,:class => 'btn btn-primary btn-md'%> |
<%= link_to 'Back', games_path,:class => 'btn btn-primary btn-md' %>

app/views/games/index.html.erb
<style>
table th{
  text-align: center;
}
</style>
<br>

<%= link_to 'New Game', new_game_path,:class => 'btn btn-primary btn-md' %>

<h2 class='tableHeader'>Games of League</h2>

<table class = 'hover-table sortable centerTable'>
  <thead>
    <tr>
      <th>Date</th>
      <th>     </th>
      <th >Game</th>
      <th>Result</th>
    </tr>
  </thead>

  <tbody>
    <% @games.order("date asc").each do |game| %>
      <tr>  
        <td><%= game.date %></td>
        <td>---------</td>
        <td><%= game.home_team.name %>
          (
          <% if game.home_team_score == -1 %>
          <%= "?"%>
          <%else%>
          <%= game.home_team_score%>
          <%end%>
          ) 
          vs <%= game.away_team.name %>
          ( 
          <%if game.away_team_score == -1 %>
          <%="?"%>
          <%else%>
          <%= game.away_team_score%>
          <%end%>
          )</td>
                 
        <td><%= game.winner %></td>
        <td><%= link_to 'Show', game ,:class => 'btn btn-primary btn-md'%></td>
        <td><%= link_to 'Edit', edit_game_path(game),:class => 'btn btn-primary btn-md' %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } ,:class => 'btn btn-danger btn-md'%></td>
        <td><%=link_to 'Bet',new_bet_path(game),:class => 'btn btn-primary btn-md' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :home_team_id %><br>
    <%= f.select :home_team_id, options_for_select(Team.all.collect{ |u| [u.name, u.id] }) %>
  </div>
  <div class="field">
    <%= f.label :away_team_id %><br>
    <%= f.select :away_team_id, options_for_select(Team.all.collect{ |u| [u.name, u.id] }), {}, {:class=>'roundUpsize'}%>
  </div>
  <div class="field">
    <%= f.label :home_team_score %><br>
    <%= f.number_field :home_team_score , :value => "-1"%>
  </div>
  <div class="field">
    <%= f.label :away_team_score %><br>
    <%= f.number_field :away_team_score, :value => "-1"%>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p>
  <strong>Home team:</strong>
  <%= @game.home_team.name %>
</p>

<p>
  <strong>Away team:</strong>
  <%= @game.away_team.name %>
</p>

<p>
  <strong>Home team score:</strong>
  <%= @game.home_team_score %>
</p>

<p>
  <strong>Away team score:</strong>
  <%= @game.away_team_score %>
</p>

<p>
  <strong>Date:</strong>
  <%= @game.date %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>