config/routes.rb
Rails.application.routes.draw do
  resources :bets
  get 'static_pages/chat'

  resources :roles
  devise_for :users
  scope "/admin" do
  resources :users
  end
  resources :categories
  resources :posts do 
    resources :comments
  end
  resources :games
  resources :competitions
  resources :teams
  get 'welcome/index'

  resources :players

  root 'welcome#index'
 

end

app/models/player.rb
class Player < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :team
  validates :name, presence: true,
                     length: { minimum: 5 }
  validates :description, presence: true,
                    length: { minimum: 5 }
  validates :picture, presence: true
                   
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  load_and_authorize_resource
  # before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    if params[:search].blank?
      @players = Player.all
    else
      @players =Player.where("name LIKE '%#{params[:search]}%'")
    end
      @players = @players.page(params[:page]).per(9)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @player = Player.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/new
  def new
    @teams = Team.all
    # @player = Player.new
  end

  # GET /players/1/edit
  def edit
    @teams = Team.all
  end

  # POST /players
  # POST /players.json
  def create
    # @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_player
    #   @player = Player.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :description, :picture, :team_id)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<!DOCTYPE html>
<%= form_for @player, :html => {:multipart => true} do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :team_id %><br>
     <%= f.select :team_id, options_for_select(Team.all.collect{ |u| [u.name, u.id] }) %>
  </div><br>
  
    <%= f.submit nil, :class => 'btn btn-primary'%>
  
<% end %>

app/views/players/edit.html.erb
<!DOCTYPE html>
<h1>Editing Player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player,:class => 'btn btn-primary btn-md' %> |
<%= link_to 'Back', players_path,:class => 'btn btn-primary btn-md' %>

app/views/players/index.html.erb
<h1>Listing Players</h1>
<br>

<%= link_to_modal 'New Player', new_player_path,:class => 'btn btn-primary btn-md' %>
<br>
<span>
  <%= form_tag players_path, method: 'get', class: 'navbar-form pull-right', role: 'search' do %>
    <div class="input-group">
      <%= text_field_tag :search, params[:search], size: 30, placeholder: "PlayerSearch", class: "form-control"%>
    </div>
    <%= submit_tag 'Search', class: 'btn btn-success' %>
  <% end %> 
</span>
<br>
<% @players.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |idea| %>
      <div class="col-md-2">
        <%=link_to_modal( image_tag(idea.picture_url, :width => 100, :height => 100), player_path(idea), :class=>"work") %>    
        <h4><%= link_to idea.name, idea %></h4>
        <%= idea.description %><br>
        <%= link_to 'Show', idea,:class => 'btn btn-primary btn-xs' %>
        <%= link_to 'Edit', edit_player_path(idea) ,:class => 'btn btn-primary btn-xs'%>
        <%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } ,:class => 'btn btn-danger btn-xs'%>
      </div>
    <% end %>
  </div>
  <br>
<% end %>
<%=paginate @players%>


  

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>
<p>
  <strong>Picture:</strong>
  <%= image_tag(@player.picture_url, :width => 150) if @player.picture.present? %>
</p>
<p>
  <strong>Description:</strong>
  <%= @player.description %>
</p>
<p>
	<strong>Team</strong>
	<%= link_to Team.find_by(id: @player.team_id).name, team_path(@player.team_id)%>
</p>



<div class="modal-footer">
  <%= link_to 'Edit', edit_player_path(@player),:class => 'btn btn-primary btn-md' %> |
  <a href="#" rel="modal:close"><button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>